import { Box, Link } from '@chakra-ui/react'
import AuthLayout from 'components/Layouts/AuthLayout'
import type { NextPage } from 'next'
import Head from 'next/head'
import NextLink from 'next/link'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>Hello From Login Page</Box>
      <NextLink href={"/focus-time"} passHref>
        <Link>/focus-time</Link>
      </NextLink>
    </div>
  )
}

export default Home
