import AuthLayout from 'components/Layouts/AuthLayout'
import type { NextPage } from 'next'
import Head from 'next/head'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthLayout>
          Hello From Auth Layout
      </AuthLayout>
    </div>
  )
}

export default Home
